name: mobile
description: PolyScrabble - 110 mobile application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: '>=2.18.6 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^1.0.2
    get_it: ^7.2.0
    rxdart: ^0.27.7
    socket_io_client: ^2.0.1
    flutter_dotenv: ^5.0.2
    provider: ^6.0.5
    http: ^0.13.5
    flutter_i18n: ^0.32.1
    image_picker: ^0.8.7
    confirm_dialog: ^1.0.1
    webview_flutter: ^4.0.7
    path: ^1.8.2
    http_parser: ^4.0.2
    badges: ^3.0.3
    fl_chart: ^0.61.0
    firebase_core: ^2.9.0
    firebase_dynamic_links: ^5.1.0
    firebase_analytics: ^10.2.0
    clipboard: ^0.1.3
    audioplayers: ^4.0.1

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/images/scrabble_logo.png
        - assets/images/test.png
        - assets/images/exchange.png
        - assets/images/crown.png
        - development.env
        - production.env
        - assets/flutter_i18n/
        - assets/audio/
        - assets/certs/server.key
        - assets/certs/server.pem
