name: mobile
description: PolyScrabble - 110 mobile application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: '>=2.18.6 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^1.0.2
    get_it: ^7.2.0
    rxdart: ^0.27.7
    intl: ^0.18.0
    socket_io_client: ^2.0.1
    flutter_dotenv: ^5.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/images/scrabble_logo.png
        - development.env
        - production.env
