// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGDPI76HYcuGJr8f53SlCH_TTTojF0Vwg',
    appId: '1:336027519857:web:ddf33af7bbf15152d644d0',
    messagingSenderId: '336027519857',
    projectId: 'scrabble-flutter',
    authDomain: 'scrabble-flutter.firebaseapp.com',
    storageBucket: 'scrabble-flutter.appspot.com',
    measurementId: 'G-D50VG1XKMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWq2CIfFXC5m45GITJ5ThANBClW5tS4pQ',
    appId: '1:336027519857:android:4e8b17a4c091647fd644d0',
    messagingSenderId: '336027519857',
    projectId: 'scrabble-flutter',
    storageBucket: 'scrabble-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoywmIFVQgdwtjiS334nkUOAYrFF1SwW8',
    appId: '1:336027519857:ios:199ab618a345d30fd644d0',
    messagingSenderId: '336027519857',
    projectId: 'scrabble-flutter',
    storageBucket: 'scrabble-flutter.appspot.com',
    iosClientId: '336027519857-2b8nls0gg819torb26jv7ra49rhuvtok.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoywmIFVQgdwtjiS334nkUOAYrFF1SwW8',
    appId: '1:336027519857:ios:199ab618a345d30fd644d0',
    messagingSenderId: '336027519857',
    projectId: 'scrabble-flutter',
    storageBucket: 'scrabble-flutter.appspot.com',
    iosClientId: '336027519857-2b8nls0gg819torb26jv7ra49rhuvtok.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );
}
